#ifndef _BEAN_VM_H
#define _BEAN_VM_H

typedef enum {
  OP_BEAN_PUSH_NIL=2,
  OP_BEAN_PUSH_FALSE,
  OP_BEAN_PUSH_TRUE,
  OP_BEAN_PUSH_STR,
  OP_BEAN_PUSH_NUM,
  OP_BEAN_INSPECT,
  OP_BEAN_BINARY_OP,
  OP_BEAN_VARIABLE_GET,
  OP_BEAN_VARIABLE_DEFINE,
  OP_BEAN_FUNCTION_DEFINE,
  OP_BEAN_FUNCTION_CALL,
  OP_BEAN_ARRAY_PUSH,
  OP_BEAN_ARRAY_ITEM,
  OP_BEAN_HASH_NEW,
  OP_BEAN_HASH_KEY,
  OP_BEAN_HASH_VALUE,
  OP_BEAN_HANDLE_PREFIX,
  OP_BEAN_HANDLE_SUFFIX
} OpCode;

int executeInstruct();

#endif
